CURRENCY = (
    ('BTC', 'Bitcoin'),
    ('ETH', 'Ethereum'),
    ('USDT', 'Tether'),
    ('BNB', 'BNB'),
    ('USDC', 'USD Coin'),
    ('XRP', 'XRP'),
    ('BUSD', 'Binance USD'),
    ('ADA', 'Cardano'),
    ('DOGE', 'Dogecoin'),
    ('MATIC', 'Polygon'),
    ('SOL', 'Solana'),
    ('OKB', 'OKB'),
    ('STETH', 'Lido Staked Ether'),
    ('DOT', 'Polkadot'),
    ('LTC', 'Litecoin'),
    ('SHIB', 'Shiba Inu'),
    ('TRX', 'TRON'),
    ('AVAX', 'Avalanche'),
    ('DAI', 'Dai'),
    ('UNI', 'Uniswap'),
    ('WBTC', 'Wrapped Bitcoin'),
    ('ATOM', 'Cosmos Hub'),
    ('TON', 'Toncoin'),
    ('LINK', 'Chainlink'),
    ('LEO', 'LEO Token'),
    ('XMR', 'Monero'),
    ('ETC', 'Ethereum Classic'),
    ('BCH', 'Bitcoin Cash'),
    ('XLM', 'Stellar'),
    ('CRO', 'Cronos'),
    ('NEAR', 'NEAR Protocol'),
    ('APE', 'ApeCoin'),
    ('QNT', 'Quant'),
    ('LDO', 'Lido DAO'),
    ('ALGO', 'Algorand'),
    ('FIL', 'Filecoin'),
    ('VET', 'VeChain'),
    ('ICP', 'Internet Computer'),
    ('HBAR', 'Hedera'),
    ('EOS', 'EOS'),
    ('MANA', 'Decentraland'),
    ('AAVE', 'Aave'),
    ('AXS', 'Axie Infinity'),
    ('LUNC', 'Terra Luna Classic'),
    ('FLOW', 'Flow'),
    ('SAND', 'The Sandbox'),
    ('FRAX', 'Frax'),
    ('APT', 'Aptos'),
    ('EGLD', 'MultiversX'),
    ('XTZ', 'Tezos'),
    ('THETA', 'Theta Network'),
    ('USDP', 'Pax Dollar'),
    ('BSV', 'Bitcoin SV'),
    ('HT', 'Huobi'),
    ('FTM', 'Fantom'),
    ('TUSD', 'TrueUSD'),
    ('KCS', 'KuCoin'),
    ('CHZ', 'Chiliz'),
    ('USDD', 'USDD'),
    ('BTT', 'BitTorrent'),
    ('TWT', 'Trust Wallet'),
    ('MKR', 'Maker'),
    ('CAKE', 'PancakeSwap'),
    ('ZEC', 'Zcash'),
    ('GRT', 'The Graph'),
    ('KLAY', 'Klaytn'),
    ('RPL', 'Rocket Pool'),
    ('MIOTA', 'IOTA'),
    ('GUSD', 'Gemini Dollar'),
    ('DASH', 'Dash'),
    ('XEC', 'eCash'),
    ('GT', 'Gate'),
    ('TKX', 'Tokenize Xchange'),
    ('BIT', 'BitDAO'),
    ('NEO', 'NEO'),
    ('CRV', 'Curve DAO'),
    ('FLR', 'Flare'),
    ('CUSDC', 'cUSDC'),
    ('OKT', 'OKC'),
    ('PAXG', 'PAX Gold'),
    ('RUNE', 'THORChain'),
    ('FXS', 'Frax Share'),
    ('SNX', 'Synthetix Network'),
    ('XAUT', 'Tether Gold'),
    ('CDAI', 'cDAI'),
    ('MINA', 'Mina Protocol'),
    ('AR', 'Arweave'),
    ('CETH', 'cETH'),
    ('OSMO', 'Osmosis'),
    ('GMX', 'GMX'),
    ('IMX', 'ImmutableX'),
    ('ZIL', 'Zilliqa'),
    ('NEXO', 'NEXO'),
    ('XRD', 'Radix'),
    ('ETHW', 'EthereumPoW'),
    ('HNT', 'Helium'),
    ('1INCH', '1inch'),
    ('XDC', 'XDC Network'),
    ('GALA', 'GALA'),
    ('COMP', 'Compound'),
    ('OP', 'Optimism'),
    ('CSPR', 'Casper Network'),
    ('BTSE', 'BTSE Token'),
    ('STX', 'Stacks'),
    ('LUNA', 'Terra'),
    ('ENS', 'Ethereum Name Service'),
    ('ENJ', 'Enjin Coin'),
    ('BAT', 'Basic Attention'),
    ('HOT', 'Holo'),
    ('DFI', 'DeFiChain'),
    ('LN', 'LINK'),
    ('LRC', 'Loopring'),
    ('DCR', 'Decred'),
    ('KAVA', 'Kava'),
    ('XEM', 'NEM'),
    ('GMT', 'STEPN'),
    ('CELO', 'Celo'),
    ('RVN', 'Ravencoin'),
    ('WOO', 'WOO Network'),
    ('CVX', 'Convex Finance'),
    ('RETH', 'Rocket Pool ETH'),
    ('NXM', 'Nexus Mutual'),
    ('BTG', 'Bitcoin Gold'),
    ('BONE', 'Bone ShibaSwap'),
    ('KSM', 'Kusama'),
    ('BGB', 'Bitget Token'),
    ('SAFEMOON', 'SafeMoon [OLD]'),
    ('IOTX', 'IoTeX'),
    ('OHM', 'Olympus'),
    ('GNO', 'Gnosis'),
    ('CEL', 'Celsius Network'),
    ('XCN', 'Chain'),
    ('OMI', 'ECOMI'),
    ('BAL', 'Balancer'),
    ('TFUEL', 'Theta Fuel'),
    ('FET', 'Fetch.ai'),
    ('QTUM', 'Qtum'),
    ('SUSHI', 'Sushi'),
    ('ROSE', 'Oasis Network'),
    ('XCH', 'Chia'),
    ('YFI', 'yearn.finance'),
    ('KDA', 'Kadena'),
    ('ELG', 'Escoin'),
    ('BAND', 'Band Protocol'),
    ('USTC', 'TerraClassicUSD'),
    ('EURT', 'Euro Tether'),
    ('CHSB', 'SwissBorg'),
    ('GLM', 'Golem'),
    ('DYDX', 'dYdX'),
    ('GLMR', 'Moonbeam'),
    ('AMP', 'Amp'),
    ('AZERO', 'Aleph Zero'),
    ('ONE', 'Harmony'),
    ('WAVES', 'Waves'),
    ('CVXCRV', 'Convex CRV'),
    ('JST', 'JUST'),
    ('BNX', 'BinaryX'),
    ('AGIX', 'SingularityNET'),
    ('EVMOS', 'Evmos'),
    ('MASK', 'Mask Network'),
    ('ANKR', 'Ankr'),
    ('HBTC', 'Huobi BTC'),
    ('CUSDT', 'cUSDT'),
    ('LUSD', 'Liquity USD'),
    ('ELON', 'Dogelon Mars'),
    ('OMG', 'OMG Network'),
    ('ASTR', 'Astar'),
    ('MSOL', 'Marinade staked SOL'),
    ('BABYDOGE', 'Baby Doge Coin'),
    ('BDX', 'Beldex'),
    ('AUDIO', 'Audius'),
    ('ZRX', '0x'),
    ('IOST', 'IOST'),
    ('ALUSD', 'Alchemix USD'),
    ('KUB', 'Bitkub Coin'),
    ('ONT', 'Ontology'),
    ('FLUX', 'Flux'),
    ('ICX', 'ICON'),
    ('RNDR', 'Render'),
    ('RSR', 'Reserve Rights'),
    ('POLY', 'Polymath'),
    ('LPT', 'Livepeer'),
    ('TEL', 'Telcoin'),
    ('DGB', 'DigiByte'),
    ('SFM', 'SafeMoon'),
    ('BICO', 'Biconomy'),
    ('SCRT', 'Secret'),
    ('EWT', 'Energy Web'),
    ('CET', 'CoinEx'),
    ('MAGIC', 'Magic'),
    ('NEST', 'Nest Protocol'),
    ('SFP', 'SafePal'),
    ('GTC', 'Gitcoin'),
    ('SC', 'Siacoin'),
    ('WAXP', 'WAX'),
    ('BORA', 'BORA'),
    ('BRISE', 'Bitgert'),
    ('MULTI', 'Multichain'),
    ('LYXE', 'LUKSO'),
    ('ZEN', 'Horizen'),
    ('EURS', 'STASIS EURO'),
    ('SGB', 'Songbird'),
    ('SXP', 'SXP'),
    ('NU', 'NuCypher'),
    ('PEOPLE', 'ConstitutionDAO'),
    ('DAG', 'Constellation'),
    ('NFT', 'APENFT'),
    ('UMA', 'UMA'),
    ('INJ', 'Injective'),
    ('RBN', 'Ribbon Finance'),
    ('SRM', 'Serum'),
    ('HIVE', 'Hive'),
    ('SYN', 'Synapse'),
    ('LSK', 'Lisk'),
    ('BLD', 'Agoric'),
    ('VVS', 'VVS Finance'),
    ('10SET', 'Tenset'),
    ('CTC', 'Creditcoin'),
    ('ERG', 'Ergo'),
    ('SKL', 'SKALE'),
    ('SLP', 'Smooth Love Potion'),
    ('KNC', 'Kyber Network Crystal'),
    ('RLC', 'iExec RLC'),
    ('GFARM2', 'Gains Farm'),
    ('OCEAN', 'Ocean Protocol'),
    ('DAO', 'DAO Maker'),
    ('BTC.B', 'Bitcoin Avalanche Bridged (BTC.b)'),
    ('TRIBE', 'Tribe'),
    ('ULT', 'Shardus'),
    ('VGX', 'Voyager VGX'),
    ('POLYX', 'Polymesh'),
    ('CKB', 'Nervos Network'),
    ('SETH2', 'sETH2'),
    ('PLA', 'PlayDapp'),
    ('ILV', 'Illuvium'),
    ('API3', 'API3'),
    ('XNO', 'Nano'),
    ('SSV', 'SSV Network'),
    ('ANT', 'Aragon'),
    ('FX', 'Function X'),
    ('PUNDIX', 'Pundi X'),
    ('NMR', 'Numeraire'),
    ('MC', 'Merit Circle'),
    ('XIDO', 'Xido Finance'),
    ('USDX', 'USDX'),
    ('LOOKS', 'LooksRare'),
    ('STSOL', 'Lido Staked SOL'),
    ('PLTC', 'PlatonCoin'),
    ('CDT', 'Blox'),
    ('WEMIX', 'WEMIX'),
    ('METIS', 'Metis'),
    ('KAS', 'Kaspa'),
    ('ALI', 'Artificial Liquid Intelligence'),
    ('DEXE', 'DeXe'),
    ('SNT', 'Status'),
    ('FLOKI', 'FLOKI'),
    ('MX', 'MX'),
    ('SYS', 'Syscoin'),
    ('MIM', 'Magic Internet Money'),
    ('PYR', 'Vulcan Forged'),
    ('CFG', 'Centrifuge'),
    ('WCFG', 'Wrapped Centrifuge'),
    ('SAVAX', 'BENQI Liquid Staked AVAX'),
    ('ANKRETH', 'Ankr Staked ETH'),
    ('JUNO', 'JUNO'),
    ('DESO', 'Decentralized Social'),
    ('ALICE', 'My Neighbor Alice'),
    ('XYO', 'XYO Network'),
    ('RAD', 'Radicle'),
    ('CTSI', 'Cartesi'),
    ('ELF', 'aelf'),
    ('MBOX', 'Mobox'),
    ('ARRR', 'Pirate Chain'),
    ('MVL', 'MVL'),
    ('PROM', 'Prom'),
    ('WIN', 'WINkLink'),
    ('CEEK', 'CEEK Smart VR'),
    ('XSUSHI', 'xSUSHI'),
    ('DENT', 'Dent'),
    ('REN', 'REN'),
    ('MXC', 'MXC'),
    ('MED', 'Medibloc'),
    ('COTI', 'COTI'),
    ('DKA', 'dKargo'),
    ('POKT', 'Pocket Network'),
    ('SPELL', 'Spell'),
    ('ALPHA', 'Alpha Venture DAO'),
    ('XPRT', 'Persistence'),
    ('HUM', 'Humanscape'),
    ('CHR', 'Chromia'),
    ('ARDR', 'Ardor'),
    ('NRV', 'Nerve Finance'),
    ('WRX', 'WazirX'),
    ('KILT', 'KILT Protocol'),
    ('REQ', 'Request'),
    ('EMAID', 'MaidSafeCoin'),
    ('ORBS', 'Orbs'),
    ('STEEM', 'Steem'),
    ('TRAC', 'OriginTrail'),
    ('ACA', 'Acala'),
    ('CVC', 'Civic'),
    ('PHB', 'Phoenix Global [OLD]'),
    ('CELR', 'Celer Network'),
    ('VERI', 'Veritaseum'),
    ('MDX', 'Mdex'),
    ('FUN', 'FUN Token'),
    ('C98', 'Coin98'),
    ('GNS', 'Gains Network'),
    ('BSW', 'Biswap'),
    ('IQ', 'IQ'),
    ('POND', 'Marlin'),
    ('XVS', 'Venus'),
    ('DOCK', 'Dock'),
    ('BFC', 'Bifrost'),
    ('HEZ', 'Hermez Network'),
    ('TSUKA', 'Dejitaru Tsuka'),
    ('SHR', 'Share'),
    ('CTK', 'Shentu'),
    ('EVER', 'Everscale'),
    ('GAL', 'Galxe'),
    ('BMEX', 'BitMEX'),
    ('RARE', 'SuperRare'),
    ('DPX', 'Dopex'),
    ('STRAX', 'Stratis'),
    ('PCX', 'ChainX'),
    ('AXL', 'Axelar'),
    ('WMT', 'World Mobile Token'),
    ('PLEX', 'PLEX'),
    ('NKN', 'NKN'),
    ('FIDU', 'Fidu'),
    ('SAITAMA', 'Saitama'),
    ('RACA', 'Radio Caca'),
    ('POWR', 'Power Ledger'),
    ('MLK', 'MiL.k Alliance'),
    ('PHA', 'Phala Network'),
    ('UQC', 'Uquid Coin'),
    ('BOBA', 'Boba Network'),
    ('SOLO', 'Sologenic'),
    ('EXRD', 'e-Radix'),
    ('BNT', 'Bancor Network'),
    ('RON', 'Ronin'),
    ('REEF', 'Reef'),
    ('SURE', 'inSure DeFi'),
    ('VTHO', 'VeThor'),
    ('STG', 'Stargate Finance'),
    ('QKC', 'QuarkChain'),
    ('HFT', 'Hashflow'),
    ('KUJI', 'Kujira'),
    ('LCX', 'LCX'),
    ('DERO', 'Dero'),
    ('CORE', 'cVault.finance'),
    ('UOS', 'Ultra'),
    ('VLX', 'Velas'),
    ('JOE', 'JOE'),
    ('AMPL', 'Ampleforth'),
    ('FLEXUSD', 'flexUSD'),
    ('TON', 'Tokamak Network'),
    ('RDPX', 'Dopex Rebate'),
    ('ECOIN', 'Ecoin'),
    ('EUL', 'Euler'),
    ('STPT', 'STP'),
    ('TEMPLE', 'TempleDAO'),
    ('CFX', 'Conflux'),
    ('LQTY', 'Liquity'),
    ('CCD', 'Concordium'),
    ('OGN', 'Origin Protocol'),
    ('POLIS', 'Star Atlas DAO'),
    ('VOLT', 'Volt Inu'),
    ('YFII', 'DFI.money'),
    ('MTL', 'Metal DAO'),
    ('QUACK', 'Rich Quack'),
    ('BOR', 'BoringDAO [OLD]'),
    ('HUNT', 'Hunt'),
    ('KEEP', 'Keep Network'),
    ('MEX', 'xExchange'),
    ('TLM', 'Alien Worlds'),
    ('KRD', 'Krypton DAO'),
    ('STMX', 'StormX'),
    ('DIVI', 'Divi'),
    ('CANTO', 'CANTO'),
    ('BETA', 'Beta Finance'),
    ('SX', 'SX Network'),
    ('CTXC', 'Cortex'),
    ('CQT', 'Covalent'),
    ('IBEUR', 'Iron Bank EURO'),
    ('SUN', 'Sun Token'),
    ('OUSD', 'Origin Dollar'),
    ('KODA', 'Koda Cryptocurrency'),
    ('REV', 'Revain'),
    ('ARK', 'ARK'),
    ('COL', 'Clash of Lilliput'),
    ('AKT', 'Akash Network'),
    ('BADGER', 'Badger DAO'),
    ('XVG', 'Verge'),
    ('XSGD', 'XSGD'),
    ('ADS', 'Adshares'),
    ('DAWN', 'Dawn Protocol'),
    ('BONK', 'Bonk'),
    ('GMT', 'GMT Token'),
    ('DODO', 'DODO'),
    ('MBX', 'Marblex'),
    ('ASD', 'AscendEx'),
    ('RIF', 'RSK Infrastructure Framework'),
    ('XCM', 'Coinmetro'),
    ('SFUND', 'Seedify.fund'),
    ('SUSD', 'sUSD'),
    ('STORJ', 'Storj'),
    ('AERGO', 'Aergo'),
    ('MFT', 'Hifi Finance [OLD]'),
    ('AXEL', 'AXEL'),
    ('SAITO', 'Saito'),
    ('MNW', 'Morpheus Network'),
    ('SWEAT', 'Sweatcoin - Sweat Economy'),
    ('OXT', 'Orchid Protocol'),
    ('MIMATIC', 'MAI'),
    ('EFI', 'Efinity'),
    ('ACH', 'Alchemy Pay'),
    ('MTRG', 'Meter Governance'),
    ('SSX', 'SOMESING Exchange'),
    ('UTK', 'Utrust'),
    ('TIME', 'chrono.tech'),
    ('STRK', 'Strike'),
    ('MOVR', 'Moonriver'),
    ('XMON', 'XMON'),
    ('COCOS', 'COCOS BCX'),
    ('AXN', 'Axion'),
    ('CUSD', 'Celo Dollar'),
    ('MBL', 'MovieBloc'),
    ('PERP', 'Perpetual Protocol'),
    ('AMA', 'MrWeb Finance [OLD]'),
    ('GODS', 'Gods Unchained'),
    ('BWO', 'Battle World'),
    ('IETH', 'Instadapp ETH'),
    ('USDK', 'USDK'),
    ('YGG', 'Yield Guild Games'),
    ('REP', 'Augur'),
    ('ZIG', 'Zignaly'),
    ('KISHU', 'Kishu Inu'),
    ('ITAMCUBE', 'CUBE'),
    ('HXRO', 'Hxro'),
    ('MTD', 'Minted'),
    ('DUSK', 'DUSK Network'),
    ('ETN', 'Electroneum'),
    ('AVINOC', 'AVINOC'),
    ('GHST', 'Aavegotchi'),
    ('ALPACA', 'Alpaca Finance'),
    ('VEGA', 'Vega Protocol'),
    ('AURABAL', 'Aura BAL'),
    ('EGC', 'EverGrow Coin'),
    ('ALBT', 'AllianceBlock'),
    ('HAY', 'Destablecoin HAY'),
    ('XCAD', 'XCAD Network'),
    ('META', 'Metadium'),
    ('FLM', 'Flamingo Finance'),
    ('POLS', 'Polkastarter'),
    ('LOOMOLD', 'Loom Network (OLD)'),
    ('DEI', 'DEI'),
    ('UFO', 'UFO Gaming'),
    ('MPL', 'Maple'),
    ('PLT', 'Poollotto.finance'),
    ('LEASH', 'Doge Killer'),
    ('FEI', 'Fei USD'),
    ('PHB', 'Phoenix Global'),
    ('SB', 'Snowbank'),
    ('SOFI', 'RAI Finance'),
    ('RAY', 'Raydium'),
    ('MATICX', 'Stader MaticX'),
    ('TT', 'ThunderCore'),
    ('ATA', 'Automata'),
    ('ATLAS', 'Star Atlas'),
    ('HC', 'HyperCash'),
    ('U', 'Unidef'),
    ('WAN', 'Wanchain'),
    ('TRB', 'Tellor'),
    ('LAT', 'PlatON Network'),
    ('TLOS', 'Telos'),
    ('LIT', 'Litentry'),
    ('BTRFLY', 'Redacted'),
    ('IDIA', 'Impossible Finance Launchpad'),
    ('QRDO', 'Qredo'),
    ('WOZX', 'Efforce'),
    ('CULT', 'Cult DAO'),
    ('VRSC', 'Verus Coin'),
    ('MELD', 'MELD'),
    ('KP3R', 'Keep3rV1'),
    ('HERO', 'Metahero'),
    ('ROOT', 'Rootkit'),
    ('STARS', 'Stargaze'),
    ('RLY', 'Rally'),
    ('GXC', 'GXChain'),
    ('FINE', 'Refinable'),
    ('LTO', 'LTO Network'),
    ('ERN', 'Ethernity Chain'),
    ('BIFI', 'Beefy.Finance'),
    ('LOKA', 'League of Kingdoms'),
    ('FITFI', 'Step App'),
    ('TRU', 'TrueFi'),
    ('GAS', 'Gas'),
    ('AVA', 'Travala.com'),
    ('CCS', 'CloutContracts'),
    ('CBAT', 'cBAT'),
    ('WNXM', 'Wrapped NXM'),
    ('BAKE', 'BakerySwap'),
    ('KMD', 'Komodo'),
    ('ARPA', 'ARPA'),
    ('BEAN', 'Bean'),
    ('AUCTION', 'Bounce'),
    ('IDEX', 'IDEX'),
    ('BLID', 'Bolide'),
    ('RAMP', 'RAMP [OLD]'),
    ('VRA', 'Verasity'),
    ('AE', 'Aeternity'),
    ('GAFI', 'GameFi'),
    ('STARL', 'StarLink'),
    ('LM', 'LeisureMeta'),
    ('BTM', 'Bytom'),
    ('MLN', 'Enzyme'),
    ('THOR', 'THORSwap'),
    ('AURA', 'Aura Finance'),
    ('DFG', 'Defigram'),
    ('CAW', 'A Hunters Dream'),
    ('SWISE', 'StakeWise'),
    ('FORTH', 'Ampleforth Governance'),
    ('DIA', 'DIA'),
    ('KOGE', 'BNB48 Club'),
    ('KAI', 'KardiaChain'),
    ('LEVER', 'LeverFi'),
    ('BOND', 'BarnBridge'),
    ('RIDE', 'holoride'),
    ('B2M', 'Bit2Me'),
    ('ORN', 'Orion Protocol'),
    ('FER', 'Ferro'),
    ('GRS', 'Groestlcoin'),
    ('TOMO', 'TomoChain'),
    ('NEBL', 'Neblio'),
    ('SBD', 'Steem Dollars'),
    ('LINA', 'Linear'),
    ('FUTURE', 'FutureCoin'),
    ('XTP', 'Tap'),
    ('BEL', 'Bella Protocol'),
    ('CERE', 'Cere Network'),
    ('MRS', 'Metars Genesis'),
    ('AURORA', 'Aurora'),
    ('AGEUR', 'agEUR'),
    ('RAIL', 'Railgun'),
    ('ETHM', 'Ethereum Meta'),
    ('UNFI', 'Unifi Protocol DAO'),
    ('UBT', 'Unibright'),
    ('SETH', 'sETH'),
    ('CXO', 'CargoX'),
    ('SPHERE', 'Sphere Finance'),
    ('INSTAR', 'INSTAR'),
    ('WILD', 'Wilder World'),
    ('RSV', 'Reserve'),
    ('REGEN', 'Regen'),
    ('HEGIC', 'Hegic'),
    ('CRE', 'Carry'),
    ('BZZ', 'Swarm'),
    ('SUPER', 'SuperVerse'),
    ('ALCX', 'Alchemix'),
    ('CLV', 'Clover Finance'),
    ('H2O', 'H2O Dao'),
    ('EUROC', 'Euro Coin'),
    ('BTS', 'BitShares'),
    ('FCT', 'Firmachain'),
    ('ICHI', 'ICHI'),
    ('ALPINE', 'Alpine F1 Team Fan Token'),
    ('VIDT', 'VIDT DAO'),
    ('GBEX', 'Globiance Exchange'),
    ('LEND', 'Aave [OLD]'),
    ('FOLD', 'Manifold Finance'),
    ('SNM', 'SONM'),
    ('MOC', 'Mossland'),
    ('FIS', 'Stafi'),
    ('CUNI', 'cUNI'),
    ('LYRA', 'Lyra Finance'),
    ('XKI', 'KI'),
    ('FEG', 'FEG BSC'),
    ('EPS', 'Ellipsis [OLD]'),
    ('CEUR', 'Celo Euro'),
    ('CHNG', 'Chainge Finance'),
    ('JEWEL', 'DeFi Kingdoms'),
    ('PSG', 'Paris Saint-Germain Fan Token'),
    ('TONIC', 'Tectonic'),
    ('HUSD', 'HUSD'),
    ('UMAMI', 'Umami'),
    ('QI', 'BENQI'),
    ('FORT', 'Forta'),
    ('RVP', 'Revolution Populi'),
    ('IXT', 'IX'),
    ('CWEB', 'Coinweb'),
    ('QUICK', 'Quickswap [OLD]'),
    ('RFR', 'Refereum'),
    ('DOLA', 'Dola'),
    ('PLU', 'Pluton'),
    ('SANTOS', 'Santos FC Fan Token'),
    ('ROUTE', 'Router Protocol'),
    ('NOIA', 'Syntropy'),
    ('REI', 'REI Network'),
    ('VITA', 'VitaDAO'),
    ('TALK', 'Talken'),
    ('ION', 'Ion'),
    ('AGLD', 'Adventure Gold'),
    ('DOME', 'Everdome'),
    ('AIOZ', 'AIOZ Network'),
    ('GAMI', 'GAMI World'),
    ('FARM', 'Harvest Finance'),
    ('ASTRAFER', 'Astrafer'),
    ('FIDA', 'Bonfida'),
    ('BAR', 'FC Barcelona Fan Token'),
    ('BOSON', 'Boson Protocol'),
    ('KLV', 'Klever'),
    ('CGS', 'Crypto Gladiator Shards'),
    ('SAI', 'Sai'),
    ('PRO', 'Propy'),
    ('XPR', 'Proton'),
    ('LAZIO', 'Lazio Fan Token'),
    ('DEP', 'DEAPCOIN'),
    ('DPI', 'DeFi Pulse Index'),
    ('BCD', 'Bitcoin Diamond'),
    ('CHO', 'Choise.com'),
    ('HYDRA', 'Hydra'),
    ('RARI', 'Rarible'),
    ('QLC', 'Kepple'),
    ('VXV', 'Vectorspace AI'),
    ('GYEN', 'GYEN'),
    ('MIR', 'Mirror Protocol'),
    ('TPT', 'TokenPocket Token'),
    ('JASMY', 'JasmyCoin'),
    ('AQT', 'Alpha Quark'),
    ('BLZ', 'Bluzelle'),
    ('KUNCI', 'Kunci Coin'),
    ('USDN', 'Neutrino USD'),
    ('SDAO', 'SingularityDAO'),
    ('GOG', 'Guild of Guardians'),
    ('SNL', 'Sport and Leisure'),
    ('FIO', 'FIO Protocol'),
    ('FIRO', 'Firo'),
    ('ZPAY', 'ZoidPay'),
    ('HARD', 'Kava Lend'),
    ('IRIS', 'IRISnet'),
    ('NULS', 'Nuls'),
    ('FEG', 'FEG'),
    ('ONIT', 'ONBUFF'),
    ('AUTO', 'Auto'),
    ('KWENTA', 'Kwenta'),
    ('BZRX', 'bZx Protocol'),
    ('UXP', 'UXD Protocol'),
    ('TKO', 'Tokocrypto'),
    ('VITE', 'Vite'),
    ('RMRK', 'RMRK'),
    ('DATA', 'Streamr'),
    ('SDN', 'Shiden Network'),
    ('MNGO', 'Mango'),
    ('PSTAKE', 'pSTAKE Finance'),
    ('ZCX', 'Unizen'),
    ('KEY', 'SelfKey'),
    ('CHESS', 'Tranchess'),
    ('VOXEL', 'Voxies'),
    ('BURGER', 'BurgerCities'),
    ('BEZOGE', 'Bezoge Earth'),
    ('BITCI', 'Bitcicoin'),
    ('MV', 'GensoKishi Metaverse'),
    ('CITY', 'Manchester City Fan Token'),
    ('MUTE', 'Mute'),
    ('PTS', 'Petals'),
    ('SQUIDGROW', 'SquidGrow'),
    ('DG', 'DeGate'),
    ('VAI', 'Vai'),
    ('SAMA', 'Moonsama'),
    ('UMEE', 'Umee'),
    ('UFT', 'UniLend Finance'),
    ('FSN', 'FUSION'),
    ('DC', 'Dogechain'),
    ('PRQ', 'PARSIQ'),
    ('GF', 'GuildFi'),
    ('OM', 'MANTRA'),
    ('AMB', 'AirDAO'),
    ('WING', 'Wing Finance'),
    ('ELA', 'Elastos'),
    ('MAP', 'MAP Protocol'),
    ('XDATA', 'Streamr XDATA'),
    ('FOX', 'ShapeShift FOX'),
    ('DF', 'dForce'),
    ('ADX', 'Ambire AdEx'),
    ('SHI', 'Shina Inu'),
    ('ITHEUM', 'Itheum'),
    ('XDAG', 'Dagger'),
    ('TOKE', 'Tokemak'),
    ('VAI', 'Vaiot'),
    ('SAMO', 'Samoyedcoin'),
    ('SOUL', 'Phantasma'),
    ('QMALL', 'Qmall'),
    ('GET', 'GET Protocol'),
    ('PIVX', 'PIVX'),
    ('BCT', 'Toucan Protocol: Base Carbon Tonne'),
    ('PINKSALE', 'PinkSale'),
    ('ES', 'Era Swap'),
    ('UPP', 'Sentinel Protocol'),
    ('COS', 'Contentos'),
    ('KNCL', 'Kyber Network Crystal Legacy'),
    ('CRTS', 'Cratos'),
    ('CATE', 'CateCoin'),
    ('DXD', 'DXdao'),
    ('ORCA', 'Orca'),
    ('MATH', 'MATH'),
    ('FPIS', 'Frax Price Index Share'),
    ('GFI', 'Goldfinch'),
    ('MCB', 'MUX Protocol'),
    ('DEXT', 'DexTools'),
    ('FRONT', 'Frontier'),
    ('BMX', 'BitMart'),
    ('PNK', 'Kleros'),
    ('BOO', 'Spookyswap'),
    ('ECOX', 'ECOx'),
    ('SDT', 'Stake DAO'),
    ('PTU', 'Pintu'),
    ('DREP', 'Drep'),
    ('AION', 'Aion'),
    ('TOR', 'TOR'),
    ('ULT', 'Ultiledger'),
    ('YOSHI', 'Yoshi.exchange'),
    ('COVAL', 'Circuits of Value'),
    ('YVE-CRVDAO', 'veCRV-DAO yVault'),
    ('AST', 'AirSwap'),
    ('STOS', 'Stratos'),
    ('CPH', 'Cypherium'),
    ('BOB', 'BOB'),
    ('PRE', 'Presearch'),
    ('DEUS', 'DEUS Finance'),
    ('ICETH', 'Interest Compounding ETH Index'),
    ('AFC', 'Arsenal Fan Token'),
    ('BEAM', 'BEAM'),
    ('ADCO', 'Advertise Coin'),
    ('CAP', 'Cap'),
    ('FWT', 'Freeway'),
    ('YLD', 'Yield App'),
    ('OOKI', 'Ooki'),
    ('VRO', 'VeraOne'),
    ('TVK', 'The Virtua Kolect'),
    ('JPEG', "JPEG'd"),
    ('DG', 'Decentral Games'),
    ('GTO', 'Gifto'),
    ('SIX', 'SIX Network'),
    ('MDT', 'Measurable Data'),
    ('TAMA', 'Tamadoge'),
    ('SWAP', 'Trustswap'),
    ('KAR', 'Karura'),
    ('MIX', 'MixMarvel'),
    ('FUSE', 'Fuse'),
    ('HNS', 'Handshake'),
    ('THALES', 'Thales'),
    ('DNT', 'district0x'),
    ('UNCX', 'UniCrypt'),
    ('CPOOL', 'Clearpool'),
    ('GBYTE', 'Obyte'),
    ('PSP', 'ParaSwap'),
    ('PDT', 'ParagonsDAO'),
    ('RISE', 'EverRise'),
    ('MLT', 'Media Licensing Token'),
    ('ZMT', 'Zipmex'),
    ('RFOX', 'RFOX'),
    ('LON', 'Tokenlon'),
    ('PROS', 'Prosper'),
    ('VIB', 'Viberate'),
    ('WISE', 'Wise'),
    ('ORAI', 'Oraichain'),
    ('ALEPH', 'Aleph.im'),
    ('VR', 'Victoria VR'),
    ('ETH2X-FLI', 'Index Coop - ETH 2x Flexible Leverage Index'),
    ('GST-SOL', 'STEPN Green Satoshi Token on Solana'),
    ('ZNN', 'Zenon'),
    ('GAL', 'Galatasaray Fan Token'),
    ('BOA', 'BOSagora'),
    ('CUBE', 'Somnium Space CUBEs'),
    ('PART', 'Particl'),
    ('YUSD', 'YUSD Stablecoin'),
    ('ANC', 'Anchor Protocol'),
    ('CROID', 'Cronos ID'),
    ('APX', 'ApolloX'),
    ('WLKN', 'Walken'),
    ('DERC', 'DeRace'),
    ('COT', 'Cosplay Token'),
    ('XAI', 'SideShift'),
    ('NIM', 'Nimiq'),
    ('NYM', 'Nym'),
    ('HTR', 'Hathor'),
    ('NPXS', 'Pundi X [OLD]'),
    ('ATOLO', 'RIZON'),
    ('BIGSB', 'BigShortBets'),
    ('CRU', 'Crust Network'),
    ('QOM', 'Shiba Predator'),
    ('HAPI', 'HAPI'),
    ('JADE', 'Jade Protocol'),
    ('BLUSD', 'Boosted LUSD'),
    ('IMPT', 'IMPT'),
    ('ROOK', 'Rook'),
    ('KLIMA', 'Klima DAO'),
    ('SPS', 'Splintershards'),
    ('GARI', 'Gari Network'),
    ('XHV', 'Haven'),
    ('OCT', 'Octopus Network'),
    ('UNIDX', 'UniDex'),
    ('SOLVE', 'SOLVE'),
    ('HOPR', 'HOPR'),
    ('NRG', 'Energi'),
    ('CRE', 'Crescent Network'),
    ('DORA', 'Dora Factory'),
    ('SLND', 'Solend'),
    ('NSBT', 'Neutrino System Base'),
    ('CUDOS', 'Cudos'),
    ('SHDW', 'Shadow Token'),
    ('SWTH', 'Carbon Protocol'),
    ('KOMPETE', 'KOMPETE Token'),
    ('XFUND', 'xFUND'),
    ('LUNR', 'Lunr'),
    ('GEIST', 'Geist Finance'),
    ('ATPAY', 'AtPay'),
    ('NCT', 'PolySwarm'),
    ('KIN', 'Kin'),
    ('RBLS', 'Rebel Bots'),
    ('ACM', 'AC Milan Fan Token'),
    ('ATM', 'Atletico Madrid Fan Token'),
    ('FRA', 'Findora'),
    ('INDEX', 'Index Cooperative'),
    ('WOOP', 'Woonkly Power'),
    ('TABOO', 'Taboo'),
    ('CVP', 'PowerPool Concentrated Voting Power'),
    ('COPI', 'Cornucopias'),
    ('ZZ', 'ZigZag'),
    ('RBIF', 'Robo Inu Finance'),
    ('$ADS', 'Alkimi'),
    ('SERO', 'SERO'),
    ('AVT', 'Aventus'),
    ('RSS3', 'RSS3'),
    ('ABT', 'Arcblock'),
    ('LBT', 'Law Blocks'),
    ('ZKS', 'ZKSpace'),
    ('VST', 'Vesta Stable'),
    ('OXEN', 'Oxen'),
    ('URUS', 'Aurox'),
    ('PPC', 'Peercoin'),
    ('SWFTC', 'SWFTCOIN'),
    ('LUFFY', 'Luffy'),
    ('MOON', 'r/CryptoCurrency Moons'),
    ('VELO', 'Velo'),
    ('JUV', 'Juventus Fan Token'),
    ('OG', 'OG Fan Token'),
    ('AMO', 'AMO Coin'),
    ('LOC', 'LockTrip'),
    ('CLO', 'Callisto Network'),
    ('HOGE', 'Hoge Finance'),
    ('TIME', 'Wonderland TIME'),
    ('FOR', 'ForTube'),
    ('DACXI', 'Dacxi'),
    ('QSP', 'Quantstamp'),
    ('SNFTS', 'Seedify NFT Space'),
    ('VTC', 'Vertcoin'),
    ('RENBTC', 'renBTC'),
    ('HAI', 'Hacken HAI'),
    ('PDEX', 'Polkadex'),
    ('IUSDC', 'Instadapp USDC'),
    ('TONE', 'TE-FOOD'),
    ('BANANA', 'ApeSwap'),
    ('INV', 'Inverse Finance'),
    ('KRL', 'KRYLL'),
    ('INST', 'Instadapp'),
    ('QI', 'Qi Dao'),
    ('XDG', 'Decentral Games Governance'),
    ('MCRT', 'MagicCraft'),
    ('VINA', 'VICUNA'),
    ('APEX', 'ApeX'),
    ('MUSD', 'mStable USD'),
    ('X2Y2', 'X2Y2'),
    ('NTX', 'NuNet'),
    ('GEL', 'Gelato'),
    ('NAKA', 'Nakamoto Games'),
    ('SOCKS', 'Unisocks'),
    ('PREMIA', 'Premia'),
    ('PNT', 'pNetwork'),
    ('DEGO', 'Dego Finance'),
    ('ZB', 'ZB'),
    ('ORB', 'Orbcity'),
    ('WICC', 'WaykiChain'),
    ('ZCN', 'Zus'),
    ('NUM', 'NUM Token'),
    ('FYN', 'Affyn'),
    ('DDX', 'DerivaDAO'),
    ('CTX', 'Cryptex Finance'),
    ('VBG', 'Vibing'),
    ('PHONON', 'Phonon DAO'),
    ('LSS', 'Lossless'),
    ('CREAM', 'Cream'),
    ('MNDE', 'Marinade'),
    ('MYST', 'Mysterium'),
    ('XDEFI', 'XDEFI'),
    ('LTX', 'Lattice'),
    ('GEAR', 'Gearbox'),
    ('FIBO', 'FibSwap DEX'),
    ('INTER', 'Inter Milan Fan Token'),
)
