# Generated by Django 3.2.16 on 2023-01-09 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_buy_fffaff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='buy',
            name='fffaff',
        ),
    ]
