# Generated by Django 3.2.16 on 2023-01-09 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_buy_aamount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='aamount',
        ),
    ]
