# Generated by Django 3.2.16 on 2023-01-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_remove_buy_aamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='aamount',
            field=models.DecimalField(blank=True, decimal_places=5, default=1, max_digits=20),
            preserve_default=False,
        ),
    ]
