# Generated by Django 3.2.16 on 2023-01-09 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_sell_aamount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sell',
            name='aamount',
        ),
    ]
