# Generated by Django 3.2.16 on 2023-01-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_remove_sell_aamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='sale_price',
            field=models.DecimalField(decimal_places=5, default=1, max_digits=20, verbose_name='Цена продажи'),
            preserve_default=False,
        ),
    ]
