# Generated by Django 3.2.16 on 2023-01-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_sell_sale_price'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='portfolio',
            constraint=models.UniqueConstraint(fields=('user', 'currency'), name='unique_user_currency'),
        ),
    ]
